#docker-compose.yml
version: '3.8'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5433"
    env_file:
      - database.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data